### ISSUE TITLE
Missing template for avatars?

### ISSUE THREAD

**Issue by Eldenroot** [SvePu/Profile-Visitors#11]
![image](https://user-images.githubusercontent.com/778890/210650215-434cb4f6-8f37-4a76-bf1f-ed2924da5109.png)

**Comment by SvePu** [comment]
....comes in next version ;)

**Comment by SvePu** [comment]
Fixed in https://github.com/SvePu/MyBB-Profile-Visitors/commit/479a139ab3c69f07d8075f17a3635ec8b341a4f3
