### ISSUE TITLE
Blank page after install - member profile

### ISSUE THREAD

**Issue by Eldenroot** [SvePu/Profile-Visitors#5]
Blank page after install - member profile

**Comment by SvePu** [comment]
Sorry can't reproduce the issue. (tested on MyBB 1.8.32 / PHP 8.1.12)

@Eldenroot Could you post your plugin settings please?

**Comment by Eldenroot** [comment]
Hmm, strange.

I have enabled only for few groups (displaying), rest is default...

Blank page - member list.

**Comment by SvePu** [comment]
Really strange ... the plugin hasn't a global or member list hook.

It only hooks into member profiles (member.php)

**Comment by Eldenroot** [comment]
Srry, my bad. I mean member_profile :(

**Comment by Eldenroot** [comment]
Still not working, tried the newest version from github.

**Comment by SvePu** [comment]
@Eldenroot could you have a look into your server error protocols to possible found the reason for this issue, please.

**Comment by SvePu** [comment]
@Eldenroot could you have a look into your server error protocols to possible found the reason for this issue, please.

**Comment by Eldenroot** [comment]
Are you on Discord?

**Comment by Eldenroot** [comment]
Fixed, somehow :)
